#include "core/platform.h"
#ifdef SWITCH_HACKS
#define AGS_OPENGL_DRIVER (AGS_PLATFORM_OS_WINDOWS || AGS_PLATFORM_OS_ANDROID || AGS_PLATFORM_OS_IOS || AGS_PLATFORM_OS_LINUX || AGS_PLATFORM_OS_MACOS)
#endif
#define AGS_OPENGL_DRIVER (0)