#ifndef __AGS_EE_AC_DYNOBJ_COLLATED_H
#define __AGS_EE_AC_DYNOBJ_COLLATED_H

#include "cn_ac_dynobj.h"

#include "ac/dynobj/all_dynamicclasses.h"
#include "ac/dynobj/all_scriptclasses.h"
#include "ac/dynobj/cc_agsdynamicobject.h"
#include "ac/dynobj/cc_audiochannel.h"
#include "ac/dynobj/cc_audioclip.h"
#include "ac/dynobj/cc_character.h"
#include "ac/dynobj/cc_dialog.h"
#include "ac/dynobj/cc_dynamicarray.h"
#include "ac/dynobj/cc_dynamicobject.h"
#include "ac/dynobj/cc_gui.h"
#include "ac/dynobj/cc_guiobject.h"
#include "ac/dynobj/cc_hotspot.h"
#include "ac/dynobj/cc_inventory.h"
#include "ac/dynobj/cc_object.h"
#include "ac/dynobj/cc_region.h"
#include "ac/dynobj/cc_serializer.h"
#include "ac/dynobj/managedobjectpool.h"
#include "ac/dynobj/scriptaudiochannel.h"
#include "ac/dynobj/scriptcamera.h"
#include "ac/dynobj/scriptcontainers.h"
#include "ac/dynobj/scriptdatetime.h"
#include "ac/dynobj/scriptdialog.h"
#include "ac/dynobj/scriptdialogoptionsrendering.h"
#include "ac/dynobj/scriptdict.h"
#include "ac/dynobj/scriptdrawingsurface.h"
#include "ac/dynobj/scriptdynamicsprite.h"
#include "ac/dynobj/scriptfile.h"
#include "ac/dynobj/scriptgui.h"
#include "ac/dynobj/scripthotspot.h"
#include "ac/dynobj/scriptinvitem.h"
#include "ac/dynobj/scriptmouse.h"
#include "ac/dynobj/scriptobject.h"
#include "ac/dynobj/scriptoverlay.h"
#include "ac/dynobj/scriptregion.h"
#include "ac/dynobj/scriptset.h"
#include "ac/dynobj/scriptstring.h"
#include "ac/dynobj/scriptsystem.h"
#include "ac/dynobj/scriptuserobject.h"
#include "ac/dynobj/scriptviewframe.h"
#include "ac/dynobj/scriptviewport.h"

#endif
