set(SDL_SHARED OFF CACHE BOOL "no shared")
set(SDL_STATIC ON CACHE BOOL "static")
set(FORCE_STATIC_VCRT ON CACHE BOOL "static windows static vcrc")
add_subdirectory(libsrc/SDL2-2.0.9 EXCLUDE_FROM_ALL)
add_library(SDL2::SDL2 ALIAS SDL2-static)
add_library(SDL2::SDL2main ALIAS SDL2main)
