include(FindPkgConfig)

find_package(SDL2 REQUIRED)

find_package(OpenGL REQUIRED)
if(OPENGL_FOUND)
    if(NOT TARGET OpenGL::GL)
        add_library(OpenGL::GL UNKNOWN IMPORTED)
        set_property(TARGET OpenGL::GL PROPERTY IMPORTED_LOCATION ${OPENGL_gl_LIBRARY})
        set_property(TARGET OpenGL::GL PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OPENGL_INCLUDE_DIR})
    endif()
endif()

find_package(Freetype REQUIRED)
if(NOT TARGET FreeType2::FreeType2)
    add_library(FreeType2::FreeType2 UNKNOWN IMPORTED)
    set_property(TARGET FreeType2::FreeType2 PROPERTY IMPORTED_LOCATION ${FREETYPE_LIBRARIES})
    set_property(TARGET FreeType2::FreeType2 PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${FREETYPE_INCLUDE_DIRS})
endif()

add_library(Allegro::Allegro STATIC IMPORTED)
set_property(TARGET Allegro::Allegro PROPERTY IMPORTED_LOCATION ${ALLEGRO_PREFIX}/lib/liballeg-debug.a)
set_property(TARGET Allegro::Allegro PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${ALLEGRO_PREFIX}/include)
set_property(TARGET Allegro::Allegro PROPERTY INTERFACE_LINK_LIBRARIES SDL2::SDL2)

add_library(alfont::alfont STATIC IMPORTED)
set_property(TARGET alfont::alfont PROPERTY IMPORTED_LOCATION ${ALFONT_PREFIX}/lib/libalfont.a)
set_property(TARGET alfont::alfont PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${ALFONT_PREFIX}/include)
set_property(TARGET alfont::alfont PROPERTY INTERFACE_LINK_LIBRARIES Allegro::Allegro)

function (pkg_target _prefix _module _target)
    pkg_check_modules(${_prefix} REQUIRED ${_module})
    add_library(${_target} INTERFACE IMPORTED)
    set_property(TARGET ${_target}  PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${${_prefix}_INCLUDEDIR}")
    set_property(TARGET ${_target}  PROPERTY INTERFACE_LINK_LIBRARIES "${${_prefix}_LIBRARIES}")
    set_property(TARGET ${_target}  PROPERTY INTERFACE_COMPILE_OPTIONS "${${_prefix}_CFLAGS}")
endfunction(pkg_target)

pkg_target(OGG ogg Ogg::Ogg)
pkg_target(THEORA theora Theora::Theora)
pkg_target(VORBIS vorbis Vorbis::Vorbis)
pkg_target(VORBISFILE vorbisfile Vorbis::VorbisFile)

# add_library(DUMB::DUMB STATIC IMPORTED)
# set_property(TARGET DUMB::DUMB PROPERTY IMPORTED_CONFIGURATIONS "Debug")
# set_property(TARGET DUMB::DUMB PROPERTY IMPORTED_LOCATION ${DUMB_PREFIX}/lib/libdumb.a)
# set_property(TARGET DUMB::DUMB PROPERTY IMPORTED_LOCATION_DEBUG ${DUMB_PREFIX}/lib/libdumbd.a)
# set_property(TARGET DUMB::DUMB PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${DUMB_PREFIX}/include)

# add_library(DUMB::AllegroDUMB STATIC IMPORTED)
# set_property(TARGET DUMB::AllegroDUMB PROPERTY IMPORTED_CONFIGURATIONS "Debug")
# set_property(TARGET DUMB::AllegroDUMB PROPERTY IMPORTED_LOCATION ${DUMB_PREFIX}/lib/libaldmb.a)
# set_property(TARGET DUMB::AllegroDUMB PROPERTY IMPORTED_LOCATION_DEBUG ${DUMB_PREFIX}/lib/libaldmd.a)
# set_property(TARGET DUMB::AllegroDUMB PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${DUMB_PREFIX}/include)
# set_property(TARGET DUMB::AllegroDUMB PROPERTY INTERFACE_LINK_LIBRARIES Allegro::Allegro DUMB::DUMB)